"""Setuptools customizations for ccc-agent builds."""

import os
import pathlib
import subprocess

from setuptools import setup
from setuptools.command.build_py import build_py as _build_py


def _git_commit(repo_root):
    try:
        output = subprocess.check_output(
            ["git", "-C", str(repo_root), "rev-parse", "HEAD"],
            stderr=subprocess.DEVNULL,
            text=True)
    except (OSError, subprocess.CalledProcessError):
        return None
    value = output.strip().lower()
    if len(value) == 40 and all(c in "0123456789abcdef" for c in value):
        return value
    return None


class build_py(_build_py):
    """Embed the build source commit into installed wheels.

    ``pip install git+https://...`` clones a specific commit and builds a wheel
    from that checkout.  The installed package no longer has ``.git`` metadata,
    so generate a tiny module during wheel build that records the cloned HEAD.
    """

    def run(self):
        super().run()
        package_dir = os.path.join(self.build_lib, "ccc_agent")
        os.makedirs(package_dir, exist_ok=True)
        commit = _git_commit(pathlib.Path(__file__).resolve().parent)
        with open(os.path.join(package_dir, "_build.py"), "w") as fh:
            fh.write("# Auto-generated by setup.py during package build.\n")
            fh.write("GIT_COMMIT = %r\n" % commit)


setup(cmdclass={"build_py": build_py})
