"""``ccc-agent setup``: wire the pip-installed runtime into a system/user env.

`pip install ccc-agent` places the Python package, the unified ``ccc-agent``
console script, and shell/plugin assets as package data. This command writes
ccc-agent-owned runtime config plus optional transparent shims:

  ccc-agent setup --system   # /etc/ccc-agent/config.json + /etc tool config
  ccc-agent setup --user     # ~/.config/ccc-agent/config.json + user config

`ccc-agent run` consumes that config and provides BranchFS/bwrap containment.
Default agent integration is persistent-config/mount-only: Codex gets a plugin
cache bind plus config enablement, Claude gets a packaged plugin seed reference,
and Hermes gets no default per-run plugin environment. Direct codex/claude/hermes
argv is not modified by setup-generated defaults.
"""

import argparse
import getpass
import json
import os
import pwd
import stat
import sys
from importlib import resources
from shutil import which

from . import branchfs_runtime
from .claude_plugin import materialize_seed


def assets_dir():
    """On-disk path to the bundled shell assets (real files in a wheel install)."""
    return str(resources.files("ccc_agent").joinpath("assets"))


def plugins_dir():
    """On-disk path to bundled agent integration assets.

    Codex assets are mounted read-only into its plugin-cache path for contained
    sessions. Setup materializes Claude's complete seed from these packaged
    assets; contained runs point Claude at it with
    ``CLAUDE_CODE_PLUGIN_SEED_DIR``. Hermes assets remain packaged for explicit
    operator use but are not injected by default.
    """
    return os.path.join(assets_dir(), "plugins")


def _make_executable(path):
    try:
        mode = os.stat(path).st_mode
        os.chmod(path, mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    except OSError:
        pass


def _resolve(name, override=None, fallbacks=()):
    if override:
        return override
    found = which(name)
    if found:
        return found
    for cand in fallbacks:
        if cand and os.path.exists(cand):
            return cand
    return name  # bare name: resolved on PATH at runtime


def _resolve_branchfs(override=None):
    if override:
        return override
    bundled = branchfs_runtime.packaged_branchfs_bin()
    if bundled:
        return bundled
    return _resolve("branchfs", None, ["/usr/local/bin/branchfs"])


def _warn_branchfs_runtime(binary):
    packaged = branchfs_runtime.is_packaged_branchfs_bin(binary)
    if packaged:
        ok, detail = branchfs_runtime.libfuse3_status()
        if not ok:
            sys.stderr.write(
                "ccc-agent setup: WARNING packaged BranchFS requires libfuse3 "
                "at runtime; install the system libfuse3 package (details: %s)\n"
                % detail)
        version = branchfs_runtime.packaged_branchfs_version()
    else:
        version = branchfs_runtime.probe_branchfs_version(binary)
    expected = branchfs_runtime.EXPECTED_BRANCHFS_VERSION
    if version and version != expected:
        sys.stderr.write(
            "ccc-agent setup: WARNING BranchFS version %s was found, but "
            "ccc-agent expects vicoslab BranchFS %s. Install "
            "ccc-agent[branchfs] or pass --branchfs-bin for the matching "
            "vicoslab/branchfs release.\n" % (version, expected))
    elif version is None and not packaged and binary != "branchfs":
        sys.stderr.write(
            "ccc-agent setup: WARNING could not verify BranchFS version for "
            "%s; ccc-agent expects vicoslab BranchFS %s. Install "
            "ccc-agent[branchfs] to use the pinned GitHub release binary.\n"
            % (binary, expected))


def _write_json(path, data):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as fh:
        json.dump(data, fh, indent=2)
    os.chmod(path, 0o644)


def _shell_single_quote(value):
    """Quote a string for POSIX shell single-quoted assignment."""
    return "'" + value.replace("'", "'\"'\"'") + "'"


def shim_path_hook_content(shim_dir):
    """Sourceable POSIX shell snippet that keeps the shim dir first on PATH."""
    quoted = _shell_single_quote(os.path.abspath(shim_dir))
    return ("#!/bin/sh\n"
            "# Generated by ccc-agent setup. Source from shell startup files to\n"
            "# keep transparent ccc-agent shims ahead of user/conda installs.\n"
            "_CCC_AGENT_SHIM_DIR=%s\n"
            "if [ -d \"$_CCC_AGENT_SHIM_DIR\" ]; then\n"
            "    _CCC_AGENT_OLD_IFS=$IFS\n"
            "    IFS=:; _CCC_AGENT_PATH=\n"
            "    for _CCC_AGENT_PART in $PATH; do\n"
            "        [ \"$_CCC_AGENT_PART\" = \"$_CCC_AGENT_SHIM_DIR\" ] && continue\n"
            "        if [ -z \"$_CCC_AGENT_PATH\" ]; then\n"
            "            _CCC_AGENT_PATH=$_CCC_AGENT_PART\n"
            "        else\n"
            "            _CCC_AGENT_PATH=$_CCC_AGENT_PATH:$_CCC_AGENT_PART\n"
            "        fi\n"
            "    done\n"
            "    IFS=$_CCC_AGENT_OLD_IFS\n"
            "    PATH=$_CCC_AGENT_SHIM_DIR${_CCC_AGENT_PATH:+:$_CCC_AGENT_PATH}\n"
            "    export PATH\n"
            "    export CCC_AGENT_SHIM_DIR=\"$_CCC_AGENT_SHIM_DIR\"\n"
            "    unset _CCC_AGENT_PATH _CCC_AGENT_PART _CCC_AGENT_OLD_IFS\n"
            "fi\n"
            "unset _CCC_AGENT_SHIM_DIR\n" % quoted)


def write_shell_path_hook(path, shim_dir):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as fh:
        fh.write(shim_path_hook_content(shim_dir))
    os.chmod(path, 0o644)
    return path


def write_conda_shim_hooks(conda_prefix, shim_dir):
    """Install env-specific conda hooks that keep ccc shims first on PATH.

    Conda activation normally prepends ``$CONDA_PREFIX/bin``. If the ccc shims
    only live in /usr/local/bin, a conda-installed ``codex``/``claude`` wins and
    bypasses containment. These hooks run after conda's PATH mutation and
    re-prepend a trusted shim directory; the shim redirects to ``ccc-agent run``
    and passes an unshimmed PATH so the contained command resolves the active
    env's real binary normally.
    """
    activate_dir = os.path.join(conda_prefix, "etc", "conda", "activate.d")
    deactivate_dir = os.path.join(conda_prefix, "etc", "conda", "deactivate.d")
    os.makedirs(activate_dir, exist_ok=True)
    os.makedirs(deactivate_dir, exist_ok=True)
    quoted = _shell_single_quote(os.path.abspath(shim_dir))
    activate = os.path.join(activate_dir, "ccc-agent-shims.sh")
    deactivate = os.path.join(deactivate_dir, "ccc-agent-shims.sh")
    with open(activate, "w") as fh:
        fh.write("#!/bin/sh\n"
                 "# Generated by ccc-agent setup. Keep containment shims ahead\n"
                 "# of $CONDA_PREFIX/bin so conda-installed agents are wrapped.\n"
                 "_CCC_AGENT_SHIM_DIR=%s\n"
                 "case \"$PATH\" in\n"
                 "    \"$_CCC_AGENT_SHIM_DIR\"|\"$_CCC_AGENT_SHIM_DIR\":*) ;;\n"
                 "    *) PATH=\"$_CCC_AGENT_SHIM_DIR:$PATH\" ;;\n"
                 "esac\n"
                 "export PATH\n"
                 "export CCC_AGENT_SHIM_DIR=\"$_CCC_AGENT_SHIM_DIR\"\n"
                 "unset _CCC_AGENT_SHIM_DIR\n" % quoted)
    with open(deactivate, "w") as fh:
        fh.write("#!/bin/sh\n"
                 "# Generated by ccc-agent setup. Remove the leading shim path\n"
                 "# this env's activate hook prepended.\n"
                 "_CCC_AGENT_SHIM_DIR=%s\n"
                 "case \"$PATH\" in\n"
                 "    \"$_CCC_AGENT_SHIM_DIR\") PATH=\"\" ;;\n"
                 "    \"$_CCC_AGENT_SHIM_DIR\":*) PATH=${PATH#\"$_CCC_AGENT_SHIM_DIR\":} ;;\n"
                 "esac\n"
                 "export PATH\n"
                 "unset CCC_AGENT_SHIM_DIR\n"
                 "unset _CCC_AGENT_SHIM_DIR\n" % quoted)
    os.chmod(activate, 0o755)
    os.chmod(deactivate, 0o755)
    return activate, deactivate


_SECRETS = [".ssh", ".gnupg", ".netrc", ".aws", ".kube", ".docker/config.json"]

CODEX_PLUGIN_NAME = "ccc"
CODEX_PLUGIN_MARKETPLACE = "ccc-agent"
CODEX_PLUGIN_VERSION = "0.2.0"
CODEX_PLUGIN_ID = "%s@%s" % (CODEX_PLUGIN_NAME, CODEX_PLUGIN_MARKETPLACE)

# Codex hook trust hashes are computed by Codex from the hook definition in
# hooks/hooks.json (not from the raw script bytes).  Keep these in sync with the
# bundled codex-ccc-containment hooks so contained runs do not stop for an
# interactive hook-trust prompt.
CODEX_HOOK_TRUSTED_HASHES = (
    ("ccc@ccc-agent:hooks/hooks.json:stop:0:0",
     "sha256:72d22a4a83b82ca16b8a5bcc60f519bc6b75773cc17f103e9acb18a028dc6998"),
)

CODEX_CONFIG_BEGIN = "# BEGIN ccc-agent Codex plugin"
CODEX_CONFIG_END = "# END ccc-agent Codex plugin"


def codex_plugin_cache_path(home):
    """In-sandbox path where Codex expects an installed plugin version."""
    return os.path.join(home, ".codex", "plugins", "cache",
                        CODEX_PLUGIN_MARKETPLACE, CODEX_PLUGIN_NAME,
                        CODEX_PLUGIN_VERSION)


def codex_plugin_config_block():
    """Managed TOML snippet enabling and trusting the ccc-agent Codex plugin.

    Use top-level dotted keys rather than opening TOML tables so the block can
    safely be prepended without changing the table context of the user's
    existing config.
    """
    lines = [
        CODEX_CONFIG_BEGIN,
        "# Codex 0.136+ loads hooks only from enabled plugins. ccc-agent keeps",
        "# this plugin enabled so contained `ccc-agent run -- codex` sessions",
        "# can load the CCC Stop hook from a read-only plugin cache bind.",
        "# It is safe to leave enabled in normal Codex runs: if the plugin cache",
        "# is absent Codex skips it, and if present the hook exits unless",
        "# CCC_AGENT_SESSION is set.",
        'plugins."%s".enabled = true' % CODEX_PLUGIN_ID,
        "# Trust only the bundled CCC hooks; do not bypass trust globally.",
    ]
    for key, trusted_hash in CODEX_HOOK_TRUSTED_HASHES:
        lines.append('hooks.state."%s".trusted_hash = "%s"'
                     % (key, trusted_hash))
    lines.extend((CODEX_CONFIG_END, ""))
    return "\n".join(lines)


def _strip_managed_codex_plugin_block(text):
    """Remove any previous ccc-agent-managed Codex config block."""
    while True:
        start = text.find(CODEX_CONFIG_BEGIN)
        if start < 0:
            return text
        line_start = text.rfind("\n", 0, start) + 1
        end = text.find(CODEX_CONFIG_END, start)
        if end < 0:
            return text[:line_start] + text[start:].lstrip("\n")
        line_end = text.find("\n", end)
        if line_end < 0:
            line_end = len(text)
        else:
            line_end += 1
        text = text[:line_start] + text[line_end:]


def _is_managed_codex_hook_key(key):
    return (key.startswith("ccc@ccc-agent:hooks/hooks.json:") or
            key.startswith("ccc-agent@ccc-agent:hooks/hooks.json:"))


def _strip_managed_codex_hook_state(text):
    """Remove stale CCC hook trust entries written by Codex or old setup runs."""
    lines = text.splitlines(True)
    out = []
    skip_table = False
    for idx, line in enumerate(lines):
        stripped = line.strip()
        if stripped == "[hooks.state]":
            # Codex writes this as a parent for nested hook-state tables.  Our
            # managed block uses dotted keys at top level; keeping an otherwise
            # empty parent table later would redeclare hooks.state and make the
            # TOML invalid.  Preserve it only if it owns direct key/value lines.
            has_direct_entries = False
            j = idx + 1
            while j < len(lines):
                candidate = lines[j].strip()
                if candidate.startswith("[") and candidate.endswith("]"):
                    break
                if candidate and not candidate.startswith("#"):
                    has_direct_entries = True
                    break
                j += 1
            if not has_direct_entries:
                continue
        if stripped.startswith('hooks.state."'):
            key = stripped[len('hooks.state."'):].split('"', 1)[0]
            if _is_managed_codex_hook_key(key):
                continue
        if stripped.startswith('[hooks.state."') and stripped.endswith('"]'):
            key = stripped[len('[hooks.state."'):-2]
            if _is_managed_codex_hook_key(key):
                skip_table = True
                continue
        if skip_table:
            if stripped.startswith("[") and stripped.endswith("]"):
                skip_table = False
            else:
                continue
        out.append(line)
    return "".join(out)


def ensure_codex_plugin_enabled(home, user=None, config_path=None):
    """Persist Codex config needed for ccc-agent's Codex plugin hooks.

    The plugin files are still supplied by ccc-agent's bwrap bind. Keeping only
    the enabled-plugin setting in Codex config is safe outside ccc-agent:
    current Codex tolerates a missing plugin cache, and the bundled hook exits
    immediately when CCC_AGENT_SESSION is absent.  System installs can write the
    same managed block to /etc/codex/config.toml so user config remains theirs.
    """
    config_path = config_path or os.path.join(home, ".codex", "config.toml")
    codex_dir = os.path.dirname(config_path)
    created_dir = not os.path.exists(codex_dir)
    under_home = os.path.abspath(config_path).startswith(
        os.path.abspath(home).rstrip(os.sep) + os.sep)
    os.makedirs(codex_dir, mode=0o700 if under_home else 0o755, exist_ok=True)
    try:
        with open(config_path) as fh:
            existing = fh.read()
    except OSError:
        existing = ""
    existing = _strip_managed_codex_plugin_block(existing)
    existing = _strip_managed_codex_hook_state(existing).lstrip("\n")
    content = codex_plugin_config_block() + existing
    if existing and not existing.endswith("\n"):
        content += "\n"
    with open(config_path, "w") as fh:
        fh.write(content)
    os.chmod(config_path, 0o644)

    # If setup runs as root in a system install and creates the user's Codex
    # config, do not leave it root-owned.
    if under_home and user and hasattr(os, "geteuid") and os.geteuid() == 0:
        try:
            pw = pwd.getpwnam(user)
        except KeyError:
            return config_path
        try:
            if created_dir:
                os.chown(codex_dir, pw.pw_uid, pw.pw_gid)
            os.chown(config_path, pw.pw_uid, pw.pw_gid)
        except OSError:
            pass
    return config_path


CLAUDE_PLUGIN_ID = CODEX_PLUGIN_ID
CLAUDE_PLUGIN_MARKETPLACE = CODEX_PLUGIN_MARKETPLACE
CLAUDE_PLUGIN_SEED_ENV = "CLAUDE_CODE_PLUGIN_SEED_DIR"
DEFAULT_CLAUDE_PLUGIN_SEED_DIR = "/opt/claude-seed"
CLAUDE_SYSTEM_SETTINGS = "/etc/claude-code/managed-settings.d/50-ccc-agent.json"


def default_claude_plugin_seed_dir(mode=None, home=None):
    """Runtime path to a pre-populated Claude Code plugin seed.

    System setup uses ``/opt/claude-seed``. User setup defaults to a writable
    per-user data directory. An explicit environment value overrides both.
    """
    configured = os.environ.get(CLAUDE_PLUGIN_SEED_ENV)
    if configured:
        return configured
    if mode == "user" and home:
        return os.path.join(home, ".local", "share", "ccc-agent",
                            "claude-seed")
    return DEFAULT_CLAUDE_PLUGIN_SEED_DIR


def _is_legacy_claude_hook_group(group):
    """Return true for settings-level hooks written by older ccc-agent setup."""
    if not isinstance(group, dict):
        return False
    for hook in group.get("hooks", ()):
        if not isinstance(hook, dict):
            continue
        command = str(hook.get("command", ""))
        if "claude-ccc-containment/hooks/ccc-" in command:
            return True
    return False


def _migrate_claude_settings_to_seed_plugin(settings):
    """Enable the seed plugin and remove obsolete duplicate integration paths."""
    settings = dict(settings or {})

    # The seed owns marketplace registration. Remove only our old declaration;
    # preserve every unrelated marketplace configured by the user/operator.
    marketplaces = settings.get("extraKnownMarketplaces")
    if isinstance(marketplaces, dict) and CLAUDE_PLUGIN_MARKETPLACE in marketplaces:
        marketplaces = dict(marketplaces)
        marketplaces.pop(CLAUDE_PLUGIN_MARKETPLACE, None)
        if marketplaces:
            settings["extraKnownMarketplaces"] = marketplaces
        else:
            settings.pop("extraKnownMarketplaces", None)

    # Hooks now live exclusively in the plugin's hooks/hooks.json. Clean only
    # the legacy ccc-agent hook groups while retaining unrelated user hooks.
    hooks = settings.get("hooks")
    if isinstance(hooks, dict):
        kept_hooks = {}
        for event, groups in hooks.items():
            if not isinstance(groups, list):
                kept_hooks[event] = groups
                continue
            kept = [group for group in groups
                    if not _is_legacy_claude_hook_group(group)]
            if kept:
                kept_hooks[event] = kept
        if kept_hooks:
            settings["hooks"] = kept_hooks
        else:
            settings.pop("hooks", None)

    enabled = settings.get("enabledPlugins")
    enabled = dict(enabled) if isinstance(enabled, dict) else {}
    enabled[CLAUDE_PLUGIN_ID] = True
    settings["enabledPlugins"] = enabled
    return settings


def ensure_claude_seed_plugin_enabled(home, user=None, settings_path=None):
    """Persist only Claude plugin enablement; installation comes from the seed."""
    settings_path = settings_path or os.path.join(home, ".claude", "settings.json")
    settings_dir = os.path.dirname(settings_path)
    under_home = os.path.abspath(settings_path).startswith(
        os.path.abspath(home).rstrip(os.sep) + os.sep)
    created_dir = not os.path.exists(settings_dir)
    os.makedirs(settings_dir, mode=0o700 if under_home else 0o755, exist_ok=True)
    try:
        with open(settings_path) as fh:
            existing = json.load(fh)
    except (OSError, ValueError):
        existing = {}
    settings = _migrate_claude_settings_to_seed_plugin(existing)
    with open(settings_path, "w") as fh:
        json.dump(settings, fh, indent=2, sort_keys=True)
        fh.write("\n")
    os.chmod(settings_path, 0o644)

    if under_home and user and hasattr(os, "geteuid") and os.geteuid() == 0:
        try:
            pw = pwd.getpwnam(user)
        except KeyError:
            return settings_path
        try:
            if created_dir:
                os.chown(settings_dir, pw.pw_uid, pw.pw_gid)
            os.chown(settings_path, pw.pw_uid, pw.pw_gid)
        except OSError:
            pass
    return settings_path


def _load_json_object(path):
    try:
        with open(path) as fh:
            value = json.load(fh)
    except (OSError, ValueError):
        return {}
    return value if isinstance(value, dict) else {}


def ensure_claude_seed_plugin_registry(home, seed_dir, user=None):
    """Initialize Claude's per-user plugin metadata from a read-only seed.

    Claude 2.1.x reconciles seed metadata after initial plugin loading. On a
    pristine home that makes a newly enabled seed plugin active only on the next
    invocation. Mirroring the seed's marketplace/install records into user state
    before launch makes the first invocation deterministic; plugin bytes remain
    in the trusted read-only seed.
    """
    # Keep the logical absolute path: this is the path mounted inside bwrap and
    # exported through CLAUDE_CODE_PLUGIN_SEED_DIR. Resolving a host symlink here
    # could write user metadata pointing at a path not present in the sandbox.
    seed_dir = os.path.abspath(seed_dir)
    seed_known_path = os.path.join(seed_dir, "known_marketplaces.json")
    seed_installed_path = os.path.join(seed_dir, "installed_plugins.json")
    seed_known = _load_json_object(seed_known_path)
    seed_installed = _load_json_object(seed_installed_path)
    seed_market = seed_known.get(CLAUDE_PLUGIN_MARKETPLACE)
    seed_plugins = seed_installed.get("plugins")
    seed_entries = (seed_plugins.get(CLAUDE_PLUGIN_ID)
                    if isinstance(seed_plugins, dict) else None)
    if not isinstance(seed_market, dict) or not isinstance(seed_entries, list):
        return None

    entry = next((dict(item) for item in seed_entries
                  if isinstance(item, dict) and
                  str(item.get("version")) == CODEX_PLUGIN_VERSION), None)
    if entry is None:
        return None
    marketplace_dir = os.path.join(seed_dir, "marketplaces",
                                   CLAUDE_PLUGIN_MARKETPLACE)
    cache_dir = os.path.join(seed_dir, "cache", CLAUDE_PLUGIN_MARKETPLACE,
                             CODEX_PLUGIN_NAME, CODEX_PLUGIN_VERSION)
    if not os.path.isfile(os.path.join(
            marketplace_dir, ".claude-plugin", "marketplace.json")):
        return None
    if not os.path.isfile(os.path.join(
            cache_dir, ".claude-plugin", "plugin.json")):
        return None

    claude_state_dir = os.path.join(home, ".claude")
    created_claude_dir = not os.path.exists(claude_state_dir)
    if created_claude_dir:
        os.makedirs(claude_state_dir, mode=0o700, exist_ok=True)
        os.chmod(claude_state_dir, 0o700)
    plugin_state_dir = os.path.join(claude_state_dir, "plugins")
    created_dir = not os.path.exists(plugin_state_dir)
    os.makedirs(plugin_state_dir, mode=0o700, exist_ok=True)
    known_path = os.path.join(plugin_state_dir, "known_marketplaces.json")
    installed_path = os.path.join(plugin_state_dir, "installed_plugins.json")

    known = _load_json_object(known_path)
    market = dict(seed_market)
    market["source"] = {"source": "directory", "path": marketplace_dir}
    market["installLocation"] = marketplace_dir
    known[CLAUDE_PLUGIN_MARKETPLACE] = market

    installed = _load_json_object(installed_path)
    installed["version"] = 2
    plugins = installed.get("plugins")
    plugins = dict(plugins) if isinstance(plugins, dict) else {}
    entry["scope"] = "user"
    entry["installPath"] = cache_dir
    plugins[CLAUDE_PLUGIN_ID] = [entry]
    installed["plugins"] = plugins

    for path, value in ((known_path, known), (installed_path, installed)):
        with open(path, "w") as fh:
            json.dump(value, fh, indent=2, sort_keys=True)
            fh.write("\n")
        os.chmod(path, 0o644)

    if user and hasattr(os, "geteuid") and os.geteuid() == 0:
        try:
            pw = pwd.getpwnam(user)
        except KeyError:
            return known_path, installed_path
        try:
            if created_claude_dir:
                os.chown(claude_state_dir, pw.pw_uid, pw.pw_gid)
            if created_dir:
                os.chown(plugin_state_dir, pw.pw_uid, pw.pw_gid)
            os.chown(known_path, pw.pw_uid, pw.pw_gid)
            os.chown(installed_path, pw.pw_uid, pw.pw_gid)
        except OSError:
            pass
    return known_path, installed_path


def build_agent_plugins(home, src_dir=None, claude_seed_dir=None):
    """Describe mount-only plugin assets used by ccc-agent run.

    Runtime config should not mutate the launched CLI argv by default. Setup and
    image-build wiring provide native plugin availability where needed:

      codex  -- /etc/codex/config.toml or ~/.codex/config.toml enables/trusts
                the plugin; ccc-agent run supplies the read-only plugin cache
                bind at Codex's installed-plugin path.
      claude -- setup materializes the packaged plugin seed; ccc-agent run
                supplies the read-only seed bind and CLAUDE_CODE_PLUGIN_SEED_DIR.
      hermes -- no default per-run plugin env injection; process-exit review
                remains authoritative.
    """
    src = src_dir or plugins_dir()
    claude_seed = os.path.abspath(
        claude_seed_dir or default_claude_plugin_seed_dir())
    codex_cache_path = codex_plugin_cache_path(home)
    codex_cache_parent = os.path.dirname(codex_cache_path)
    return {
        "codex": {
            "src": os.path.join(src, "codex-ccc-containment"),
            "sandbox_path": codex_cache_path,
            "ensure_dirs": [codex_cache_parent],
            "plugin_id": CODEX_PLUGIN_ID,
        },
        "claude": {
            "src": claude_seed,
            "sandbox_path": claude_seed,
            "setenv": {CLAUDE_PLUGIN_SEED_ENV: claude_seed},
            "plugin_id": CLAUDE_PLUGIN_ID,
        },
    }


def build_agent_state_binds(home):
    """Default shared direct state for agent tools, outside BranchFS."""
    paths = (
        ".codex", ".claude", ".hermes",
        ".claude.json", ".local/bin/codex", ".local/bin/claude",
        ".local/share/claude", ".local/state/claude",
        ".cache/claude-cli-nodejs",
    )
    return [os.path.join(home, path) for path in paths]


def build_config(mode, user, home, branchfs_bin, bwrap_bin, state_dir,
                 storage_root="/storage", branch_store="/opt/branchfs_branches",
                 container_name="", claude_seed_dir=None):
    """Assemble the runtime config.json (bwrap confinement by default).

    System mode models CCC's storage layout: the whole of ``/storage`` is the
    single BranchFS underlay (read-through), branched ONCE into a node-local
    delta store, and mounted back at ``/storage`` inside the sandbox.  CCC also
    bind-mounts the user's home to the same bytes as
    ``/storage/user/<container>`` -- so instead of branching that data a second
    time, we point ``$HOME`` at that subdir of the single branch (``home_subdir``
    on the root drives the in-sandbox ``$HOME`` bind; the top-level
    ``home_subdir`` drives the policy alias ``/home/<user>`` ->
    ``/storage/user/<container>``).  The store and state_dir therefore MUST live
    outside ``/storage`` (else BranchFS would branch its own state and the agent
    would see it)."""
    if mode == "system":
        container = container_name or user
        home_rel = "user/%s" % container                     # rel to /storage branch
        home_abs = "%s/%s" % (storage_root.rstrip("/"), home_rel)
        hide_paths = ["%s/%s" % (home_rel, s) for s in _SECRETS]
        # If state_dir happens to sit under the underlay, hide it from the view.
        sr = storage_root.rstrip("/")
        if state_dir.rstrip("/").startswith(sr + "/"):
            hide_paths.append(state_dir.rstrip("/")[len(sr) + 1:])
        root = {
            "name": "storage",
            "base": storage_root,                            # /storage (read-through)
            "store": os.path.join(branch_store, "storage"),  # node-local deltas
            "visible": storage_root,                         # mounted back at /storage
            "home_subdir": home_rel,                         # branch/<rel> -> /home/<user>
            "hide_paths": hide_paths,
        }
        top_home_subdir = container                          # alias /home/<user> -> /storage/user/<container>
        ignore = ["%s/.cache*" % home_abs]
    else:  # user mode: protect the real home
        root = {
            "name": "home", "base": home, "store": os.path.join(state_dir,
                                                                "stores", "home"),
            "visible": home, "home_subdir": "",
            "hide_paths": _SECRETS + [".ccc-agent"],
        }
        top_home_subdir = ""
        ignore = [os.path.join(home, ".cache*")]
    agent_plugins = build_agent_plugins(
        home, claude_seed_dir=(
            claude_seed_dir or default_claude_plugin_seed_dir(mode, home)))
    return {
        "_comment": "Generated by ccc-agent setup. Keep root-owned and not "
                    "writable by agents.",
        "state_dir": state_dir,
        "backend": "branchfs",
        "branchfs_bin": branchfs_bin,
        "branchfs_timeout_seconds": 30,
        "user": user,
        "home_subdir": top_home_subdir,
        "_workspace_comment": (
            "Launch workspace is per invocation: ccc-agent run defaults to "
            "the caller's current directory; pass --workspace to override."),
        "confinement": "bwrap",
        "bwrap_bin": bwrap_bin,
        "bwrap_proc_mode": "bind",
        "_runtime_comment": "Re-expose the agent binary/runtime read-only at a "
                            "NON-view dest (e.g. '/path/to/agent:/opt/agent'). "
                            "The full invocation/container environment is "
                            "inherited by default. Use bwrap_unsetenv for "
                            "explicit removals and bwrap_setenv for trusted "
                            "overrides.",
        "bwrap_ro_binds": [],
        "bwrap_unsetenv": [],
        "bwrap_setenv": {},
        "_agent_state_comment": "By default Codex/Hermes state plus Codex/"
                                "Claude Code local launcher/runtime paths "
                                "(~/.claude, ~/.claude.json, "
                                "~/.local/bin/codex, ~/.local/bin/claude, "
                                "~/.local/share/claude, "
                                "~/.local/state/claude, and "
                                "~/.cache/claude-cli-nodejs) are shared rw "
                                "system state, direct-bound over the BranchFS "
                                "home view and never committed or rolled back "
                                "by ccc-agent. Codex/Claude/Hermes own their "
                                "own concurrent access. Set "
                                "protect_agent_state=true or run with "
                                "--protect-agent-state to keep these paths in "
                                "BranchFS review instead.",
        "protect_agent_state": False,
        "ensure_agent_state_dirs": True,
        "agent_state_binds": build_agent_state_binds(home),
        "_cred_comment": "Agent config/state paths such as ~/.codex, "
                         "~/.claude, ~/.claude.json, Codex/Claude .local "
                         "binary/state/cache, and ~/.hermes are direct shared "
                         "rw agent_state_binds by default, so real agents can "
                         "create logs, sessions, caches, config, and refreshed "
                         "tokens without BranchFS merge policy. Use cred_mounts "
                         "only for narrow special-case read-only overlays; do "
                         "not bind the whole agent state dirs read-only by "
                         "default.",
        "cred_mounts": [],
        "cred_mask": [],
        "cred_env": {},
        "_agent_plugins_comment": "Mount-only CCC plugin assets for tools that "
                                  "load persistent config. Setup enables/"
                                  "trusts Codex and materializes Claude's "
                                  "packaged plugin seed; ccc-agent run "
                                  "supplies read-only plugin asset binds plus "
                                  "Claude's documented plugin seed env. No "
                                  "default entry appends agent CLI argv.",
        "agent_hook_mode": "plugins",
        "agent_plugins": agent_plugins,
        "roots": [root],
        "hide_patterns": [".env", ".env.*", "*.pem", "id_rsa*", "id_ed25519*",
                          "credentials.json"],
        "policy": {"mode": "workspace-auto", "ignore_patterns": ignore},
    }


def main(argv=None, prog="ccc-agent setup"):
    parser = argparse.ArgumentParser(
        prog=prog,
        description="Wire the installed ccc-agent runtime (config + hooks).")
    parser.add_argument("--system", action="store_true",
                        help="system install (/etc/ccc-agent; root)")
    parser.add_argument("--user", action="store_true",
                        help="user install (~/.config/ccc-agent)")
    parser.add_argument("--config", help="config.json path (override)")
    parser.add_argument("--user-name", help="agent user (default: current)")
    parser.add_argument("--branchfs-bin")
    parser.add_argument("--bwrap-bin")
    parser.add_argument("--state-dir")
    parser.add_argument("--storage-root", default="/storage",
                        help="real BranchFS underlay (system mode); branched once")
    parser.add_argument("--branch-store", default="/opt/branchfs_branches",
                        help="node-local dir for BranchFS deltas (must be OUTSIDE "
                             "--storage-root)")
    parser.add_argument("--container-name",
                        help="CCC container name; $HOME maps to "
                             "<storage-root>/user/<container> (default: $CONTAINER_NAME)")
    parser.add_argument("--no-agent-plugins", "--no-hooks", dest="no_plugins",
                        action="store_true",
                        help="omit the confined-only CCC agent plugin entries "
                             "(--no-hooks kept as a deprecated alias)")
    parser.add_argument("--protect-agent-state", action="store_true",
                        help="generate config with Codex/Hermes state and "
                             "Claude Code runtime paths kept inside "
                             "BranchFS review instead of direct shared rw binds")
    parser.add_argument("--enable-shims", action="store_true",
                        help="symlink the transparent agent PATH shims")
    parser.add_argument("--shim-agents", default="codex claude hermes opencode")
    parser.add_argument("--link-dir", default="/usr/local/bin")
    parser.add_argument("--shell-path-hook",
                        help="write a sourceable shell snippet that prepends "
                             "--link-dir to PATH (for profile/rc integration)")
    parser.add_argument("--codex-config", help=argparse.SUPPRESS)
    parser.add_argument("--claude-settings", help=argparse.SUPPRESS)
    parser.add_argument("--claude-plugin-seed-dir", help=argparse.SUPPRESS)
    parser.add_argument("--ssh-shell-router",
                        help="symlink the bundled SSH shell router to this "
                             "stable executable path")
    parser.add_argument("--conda-prefix",
                        help="conda env prefix for --conda-activate-shims "
                             "(default: $CONDA_PREFIX)")
    parser.add_argument("--conda-activate-shims", action="store_true",
                        help="write conda activate/deactivate hooks that prepend "
                             "--link-dir so shims win over $CONDA_PREFIX/bin")
    args = parser.parse_args(argv)

    mode = "user" if args.user and not args.system else "system"
    assets = assets_dir()
    hooks = os.path.join(assets, "hooks")
    shims = os.path.join(assets, "shims")
    for name in os.listdir(hooks):
        _make_executable(os.path.join(hooks, name))
    for name in os.listdir(shims):
        _make_executable(os.path.join(shims, name))
    # Plugin-bundled hook scripts must stay executable through the read-only
    # bwrap mount (pip can drop the +x bit on package data).
    for root, _dirs, files in os.walk(plugins_dir()):
        for name in files:
            if name.endswith(".sh"):
                _make_executable(os.path.join(root, name))

    user = args.user_name or os.environ.get("USER_NAME") or getpass.getuser()
    container_name = args.container_name or os.environ.get("CONTAINER_NAME") or ""
    if mode == "system":
        home = "/home/%s" % user
        # The state_dir holds the BranchFS *mountpoints*, so it MUST sit where the
        # CCC FUSE sidecar can mount -- i.e. under a Docker bind mount. The sidecar
        # translates client->host paths and refuses the container's overlay, so a
        # path like /opt/... fails the mount with EPERM (even as root: there is no
        # host-side bind mount to mount into). /storage/user is always such a bind
        # mount; it is inside the /storage underlay but build_config hides it from
        # the branch so BranchFS never recurses into it. For node-local speed,
        # point --state-dir at a bind-mounted local scratch, e.g.
        # /storage/local/ssd/.ccc-agent.
        state_dir = args.state_dir or "/storage/user/.ccc-agent"
        config_file = args.config or "/etc/ccc-agent/config.json"
    else:
        home = os.path.expanduser("~")
        state_dir = args.state_dir or os.path.join(home, ".ccc-agent")
        config_file = args.config or os.path.join(
            home, ".config", "ccc-agent", "config.json")

    branchfs_bin = _resolve_branchfs(args.branchfs_bin)
    _warn_branchfs_runtime(branchfs_bin)
    bwrap_bin = _resolve("bwrap", args.bwrap_bin)

    claude_seed_dir = (args.claude_plugin_seed_dir or
                       default_claude_plugin_seed_dir(mode, home))
    config = build_config(mode, user, home, branchfs_bin, bwrap_bin,
                          state_dir, args.storage_root, args.branch_store,
                          container_name, claude_seed_dir=claude_seed_dir)
    if args.protect_agent_state:
        config["protect_agent_state"] = True
    if args.no_plugins:
        config["agent_plugins"] = {}
        config["agent_hook_mode"] = "disabled"
    else:
        codex_config_path = (args.codex_config or
                             ("/etc/codex/config.toml" if mode == "system"
                              else None))
        claude_settings_path = (args.claude_settings or
                                (CLAUDE_SYSTEM_SETTINGS if mode == "system"
                                 else None))
        codex_config = ensure_codex_plugin_enabled(
            home, user=user, config_path=codex_config_path)
        materialize_seed(claude_seed_dir)
        claude_settings = ensure_claude_seed_plugin_enabled(
            home, user=user, settings_path=claude_settings_path)
        claude_registry = ensure_claude_seed_plugin_registry(
            home, claude_seed_dir, user=user)
        if not claude_registry:
            raise RuntimeError("failed to initialize materialized Claude plugin seed")
        sys.stderr.write(
            "ccc-agent setup: materialized Claude plugin seed from packaged "
            "assets at %s\n" % claude_seed_dir)
        sys.stderr.write(
            "ccc-agent setup: agent plugin assets under %s are mounted "
            "read-only when needed\n" % plugins_dir())
        sys.stderr.write(
            "ccc-agent setup: ensured Codex plugin enablement in %s\n"
            % codex_config)
        sys.stderr.write(
            "ccc-agent setup: ensured Claude seed-plugin enablement in %s\n"
            % claude_settings)
        sys.stderr.write(
            "ccc-agent setup: initialized Claude plugin registry from %s\n"
            % claude_seed_dir)

    _write_json(config_file, config)
    sys.stderr.write("ccc-agent setup: wrote %s\n" % config_file)

    if args.enable_shims:
        os.makedirs(args.link_dir, exist_ok=True)
        shim = os.path.join(shims, "ccc-agent-shim.sh")
        for agent in args.shim_agents.split():
            link = os.path.join(args.link_dir, agent)
            try:
                if os.path.islink(link) or os.path.exists(link):
                    os.unlink(link)
                os.symlink(shim, link)
            except OSError as exc:
                sys.stderr.write("ccc-agent setup: shim %s failed: %s\n"
                                 % (agent, exc))
        if args.shell_path_hook:
            hook_path = write_shell_path_hook(args.shell_path_hook, args.link_dir)
            sys.stderr.write("ccc-agent setup: wrote shim PATH hook %s\n"
                             % hook_path)
        if args.ssh_shell_router:
            router_src = os.path.join(shims, "ccc-agent-ssh-shell-router.sh")
            router_link = args.ssh_shell_router
            os.makedirs(os.path.dirname(router_link), exist_ok=True)
            try:
                if os.path.islink(router_link) or os.path.exists(router_link):
                    os.unlink(router_link)
                os.symlink(router_src, router_link)
                sys.stderr.write("ccc-agent setup: linked SSH shell router %s\n"
                                 % router_link)
            except OSError as exc:
                sys.stderr.write("ccc-agent setup: SSH shell router %s failed: %s\n"
                                 % (router_link, exc))

    if args.conda_activate_shims:
        conda_prefix = args.conda_prefix or os.environ.get("CONDA_PREFIX")
        if not conda_prefix:
            sys.stderr.write("ccc-agent setup: --conda-activate-shims needs "
                             "--conda-prefix or CONDA_PREFIX\n")
            return 2
        activate, deactivate = write_conda_shim_hooks(conda_prefix, args.link_dir)
        sys.stderr.write("ccc-agent setup: wrote conda shim hooks %s and %s\n"
                         % (activate, deactivate))

    sys.stderr.write("ccc-agent setup: done (%s mode)\n" % mode)
    return 0


if __name__ == "__main__":
    sys.exit(main())
